server:
  port: 8091
spring:
  application: ecommerce-client-application
security:
  oauth2:
    client:
      clientId: 233668646673605
      clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
      accessTokenUri: https://localhost:8090/oauth/token
      userAuthorizationUri: https://localhost:8090/oauth/authorize
      #below comments applies for auto creating auth and resource server like FB oauth itself
      #accessTokenUri: https://graph.facebook.com/oauth/access_token
      #userAuthorizationUri: https://www.facebook.com/dialog/oauth
      #tokenName: oauth_token
      #authenticationScheme: query
      #clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me